package blueprint

// cidrsubnetGoSource is the real, deterministic Go port of Terraform's
// own built-in `cidrsubnet(prefix, newbits, netnum)` function (UBI-125's
// own itemized scope: "Built-in functions used inside these blocks need
// porting as real generated helper functions alongside the translated
// loop"). Emitted verbatim into a converted blueprint's own generated Go
// package (go/cidrsubnet.go), NEVER into sdk/go's own runtime -- matching
// UBI-129's own established "for_each needs zero new sdk/go runtime
// construct" precedent (docs/blueprint.md): a ported built-in function is
// blueprint-package-private generated code, not a shared SDK primitive,
// exactly like the per-resource ResourceBinding/Config struct pair
// bindings.go already generates.
//
// Algorithm matches HashiCorp's own documented semantics exactly (and is
// verified against its own doc examples in cidrsubnet_test.go): extend
// prefix's own network mask by newbits, then set netnum into the newly
// available high-order bits. Panics (rather than returning an error) on
// a malformed prefix or an out-of-range newbits/netnum -- the SAME
// "invalid input is a hard failure, not a soft one" behavior Terraform's
// own cidrsubnet has at apply time; a Config field's own expression
// context (a single value slot inside a struct literal) has no room for
// an idiomatic Go (value, error) return here, matching bindings.go's own
// "every Config field is any" convention already accepting the same
// class of trade-off.
//
// Go codegen only, this ticket -- TS/Python porting is a real, named,
// NOT-silently-done follow-up (docs/blueprint.md's "Terraform module
// conversion" section states this explicitly): a converted blueprint
// using cidrsubnet() can only be built --lang go until that follow-up
// lands; GenerateTS/GeneratePython (tsgen.go/pygen.go) hard-refuse a
// draft containing a $fn marker rather than silently ignoring it (see
// their own renderAny).
const cidrsubnetGoSource = `// Code generated by ` + "`ubx blueprint convert --from-terraform`" + `. DO NOT EDIT.
package %s

import (
	"fmt"
	"math/big"
	"net"
)

// cidrsubnet is a deterministic Go port of Terraform's own built-in
// cidrsubnet() function (ubx blueprint convert, UBI-125): calculates a
// subnet address within a given IP network address prefix by extending
// the prefix's own mask by newbits and setting netnum into the newly
// available high-order bits.
func cidrsubnet(prefix string, newbits, netnum int) string {
	_, network, err := net.ParseCIDR(prefix)
	if err != nil {
		panic(fmt.Sprintf("cidrsubnet: invalid prefix %%q: %%v", prefix, err))
	}
	ones, bits := network.Mask.Size()
	newOnes := ones + newbits
	if newbits < 0 || newOnes > bits {
		panic(fmt.Sprintf("cidrsubnet: not enough address space to add %%d bits to a /%%d prefix", newbits, ones))
	}
	if netnum < 0 || (newbits < 64 && uint64(netnum) >= uint64(1)<<uint(newbits)) {
		panic(fmt.Sprintf("cidrsubnet: netnum %%d does not fit in %%d bits", netnum, newbits))
	}

	ip := network.IP.To4()
	if ip == nil {
		ip = network.IP.To16()
	}

	ipInt := new(big.Int).SetBytes(ip)
	shift := uint(bits - newOnes)
	netnumInt := new(big.Int).Lsh(big.NewInt(int64(netnum)), shift)
	ipInt.Or(ipInt, netnumInt)

	resultBytes := ipInt.Bytes()
	full := make([]byte, bits/8)
	copy(full[len(full)-len(resultBytes):], resultBytes)

	return fmt.Sprintf("%%s/%%d", net.IP(full).String(), newOnes)
}
`
