// Command probegen generates conformance/findings_generated.go's own
// GeneratedFindings slice — the hermetic-tier probe generator's own
// output (conformance.ProbeSchema), run for real against every provider
// this project currently has a pinned version for
// (conformance.PinnedProviderVersions), committed as real, versioned
// data (UBI-50 session 4, docs/conformance-harness.md's own "Verdict
// write-back" amendment).
//
// Unlike conformance/gentool (which reads only conformance.Registry's
// own already-in-memory Go data, no network at all), this tool needs
// real network access to registry.opentofu.org to acquire any
// not-yet-locally-cached provider version — the identical, already-
// accepted exception every RequireLive-gated provider-acquire test in
// this package already carries. Never wired to a `//go:generate`
// directive for that reason (a plain `go generate ./...` must stay
// fully offline) — run manually:
//
//	go run ./conformance/probegen -out conformance/findings_generated.go
//
// Re-run whenever conformance.PinnedProviderVersions bumps a version, or
// whenever conformance/probe.go's own probe logic changes — the
// generated file's own diff is exactly the "rerun on version bump"
// delta docs/conformance-harness.md's own design describes, made
// concrete (a real `git diff` on a real committed file), even though
// the automated DIFF-AND-FLAG machinery that section also designs is
// still unbuilt (see that document's own "What this doesn't yet cover").
package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"time"

	"github.com/ubiquex/ubiquex/conformance"
	"github.com/ubiquex/ubiquex/provider"
)

func main() {
	out := flag.String("out", "", "output path for the generated Go source")
	flag.Parse()
	if *out == "" {
		fmt.Fprintln(os.Stderr, "probegen: -out is required")
		os.Exit(2)
	}

	var sources []string
	for source := range conformance.PinnedProviderVersions {
		sources = append(sources, source)
	}
	sort.Strings(sources)

	var all []conformance.Finding
	for _, source := range sources {
		version := conformance.PinnedProviderVersions[source]
		findings, typeCount, err := probeOne(source, version)
		if err != nil {
			fmt.Fprintf(os.Stderr, "probegen: %s@%s: %v\n", source, version, err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "probegen: %s@%s: %d resource types, %d findings\n", source, version, typeCount, len(findings))
		all = append(all, findings...)
	}

	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by conformance/probegen. DO NOT EDIT by hand --")
	fmt.Fprintln(&b, "// re-run `go run ./conformance/probegen -out conformance/findings_generated.go`")
	fmt.Fprintln(&b, "// (needs real network access to registry.opentofu.org to acquire any")
	fmt.Fprintln(&b, "// not-yet-cached provider version; no cloud account/credentials at all --")
	fmt.Fprintln(&b, "// GetProviderSchema only).")
	fmt.Fprintln(&b, "//")
	fmt.Fprintln(&b, "// GeneratedFindings is the hermetic tier's own machine-verified BASE")
	fmt.Fprintln(&b, "// LAYER (docs/conformance-harness.md's own \"Verdict write-back\" amendment,")
	fmt.Fprintln(&b, "// UBI-50 session 4) -- every incomplete-read/sensitive-underflag/undriftable")
	fmt.Fprintln(&b, "// Finding conformance.ProbeSchema produces against every real, currently-")
	fmt.Fprintln(&b, "// onboarded provider's own pinned schema (conformance.PinnedProviderVersions),")
	fmt.Fprintln(&b, "// at generation time. Layer this against conformance.Registry's own 154")
	fmt.Fprintln(&b, "// hand-written, human-verified TypeSpec entries via conformance.LayerFindings")
	fmt.Fprintln(&b, "// (conformance.AllVerdicts is the ready-made combination of both) -- never")
	fmt.Fprintln(&b, "// read this slice alone as the full picture; the hand-verified layer is a")
	fmt.Fprintln(&b, "// strictly higher tier of confidence, per docs/conformance-harness.md's own")
	fmt.Fprintln(&b, "// \"Layering, never replacing\" rule.")
	fmt.Fprintln(&b, "package conformance")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "// Generated %s against: ", time.Now().UTC().Format("2006-01-02"))
	for i, source := range sources {
		if i > 0 {
			fmt.Fprint(&b, ", ")
		}
		fmt.Fprintf(&b, "%s@%s", source, conformance.PinnedProviderVersions[source])
	}
	fmt.Fprintln(&b, ".")
	fmt.Fprintf(&b, "var GeneratedFindings = []Finding{ // %d entries\n", len(all))
	for _, f := range all {
		fmt.Fprintf(&b, "\t{Source: %q, Version: %q, Type: %q, Verb: %q, Class: %s, Tier: %s, Confidence: %s, Detail: %q},\n",
			f.Source, f.Version, f.Type, f.Verb, classIdent(f.Class), tierIdent(f.Tier), confidenceIdent(f.Confidence), f.Detail)
	}
	fmt.Fprintln(&b, "}")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "probegen: formatting generated source: %v\n", err)
		os.Exit(2)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "probegen: %v\n", err)
		os.Exit(2)
	}
}

// probeOne acquires source@version's real schema (free, no credentials
// -- GetProviderSchema only, the identical standard every hermetic probe
// already holds to) and runs conformance.ProbeSchema against it.
func probeOne(source, version string) (findings []conformance.Finding, typeCount int, err error) {
	src, err := provider.ParseSource(source)
	if err != nil {
		return nil, 0, err
	}
	ctx, cancel := context.WithTimeout(context.Background(), 180*time.Second)
	defer cancel()
	result, err := provider.Acquire(ctx, src, version)
	if err != nil {
		return nil, 0, fmt.Errorf("acquire: %w", err)
	}
	client, err := provider.Launch(ctx, result.Path)
	if err != nil {
		return nil, 0, fmt.Errorf("launch: %w", err)
	}
	defer client.Close()
	schemas, err := client.Provider.Schema(ctx)
	if err != nil {
		return nil, 0, fmt.Errorf("schema: %w", err)
	}
	return conformance.ProbeSchema(source, version, schemas), len(schemas.Resources), nil
}

func classIdent(c conformance.FindingClass) string {
	switch c {
	case conformance.FindingIncompleteRead:
		return "FindingIncompleteRead"
	case conformance.FindingSensitiveUnderflag:
		return "FindingSensitiveUnderflag"
	case conformance.FindingDestroyLie:
		return "FindingDestroyLie"
	case conformance.FindingUndriftable:
		return "FindingUndriftable"
	default:
		panic("probegen: unknown FindingClass " + string(c))
	}
}

func tierIdent(t conformance.Tier) string {
	switch t {
	case conformance.TierHermetic:
		return "TierHermetic"
	case conformance.TierLive:
		return "TierLive"
	default:
		panic("probegen: unknown Tier " + string(t))
	}
}

func confidenceIdent(c conformance.Confidence) string {
	switch c {
	case conformance.Candidate:
		return "Candidate"
	case conformance.Confirmed:
		return "Confirmed"
	default:
		panic("probegen: unknown Confidence " + string(c))
	}
}
