// Package ts is the TypeScript template half of docs/sdk.md's own
// "Codegen design": ir.ResourceType (language-neutral, wire-name-only) ->
// idiomatic TypeScript bindings. This is the only package in
// sdk/codegen that knows what "idiomatic TypeScript" means -- camelCase
// property names, interface declarations, a runtime field-map descriptor
// -- none of which leaks back into sdk/codegen/ir itself.
package ts

import (
	"fmt"
	"sort"
	"strings"

	"github.com/ubiquex/ubiquex/sdk/codegen/ir"
)

// GeneratedFile renders one TypeScript module covering every resource
// type declared by one provider source+version -- one file per provider
// source, never per-resource-type (docs/sdk.md's own "ubx sdk gen" design:
// a real provider owns dozens to hundreds of types; one cohesive,
// reviewable, git-committed file per source matches that better than a
// file explosion). types is sorted by WireType here, defensively, even if
// a caller already passed a sorted slice -- codegen output must never
// depend on caller-supplied ordering (determinism is a feature,
// CLAUDE.md's own standing rule).
func GeneratedFile(source, version string, types []*ir.ResourceType) (string, error) {
	sorted := make([]*ir.ResourceType, len(types))
	copy(sorted, types)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].WireType < sorted[j].WireType })

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by `ubx sdk gen` from %s@%s. DO NOT EDIT.\n", source, version)
	b.WriteString("// This file is committed to git like any other reviewable generated code\n")
	b.WriteString("// (docs/sdk.md — \"ubx sdk gen: local, pinned, offline-after-generation\") --\n")
	b.WriteString("// re-run `ubx sdk gen` to regenerate after a provider version bump.\n")
	fmt.Fprintf(&b, "export const __ubxSourceProvenance = { source: %q, version: %q } as const;\n\n", source, version)
	b.WriteString("import type { Computed, FieldMap, ResourceBinding } from \"@ubx/sdk\";\n\n")

	for _, rt := range sorted {
		if err := renderResource(&b, rt); err != nil {
			return "", fmt.Errorf("sdk/codegen/templates/ts: %s: %w", rt.WireType, err)
		}
	}

	return b.String(), nil
}

// renderResource writes one resource type's full binding: nested object
// interfaces (as needed, deepest-first isn't required -- TS interface
// declarations are order-independent), the settable Config interface,
// the all-fields Attrs interface, and the runtime descriptor object
// resource() actually reads at evaluation time.
func renderResource(b *strings.Builder, rt *ir.ResourceType) error {
	pascalName, err := pascalCase(rt.WireType)
	if err != nil {
		return err
	}

	r := &resourceRenderer{pascalName: pascalName}
	for _, f := range rt.Fields {
		if err := r.collectNestedInterfaces(f, pascalName); err != nil {
			return err
		}
	}
	for _, decl := range r.nestedDecls {
		b.WriteString(decl)
		b.WriteString("\n")
	}

	// Config interface: settable fields only (Required or Optional --
	// see fieldIsSettable's own doc comment for the Computed-only
	// exclusion this implements).
	fmt.Fprintf(b, "export interface %sConfig {\n", pascalName)
	for _, f := range rt.Fields {
		if !fieldIsSettable(f) {
			continue
		}
		idiomatic, err := camelCase(f.WireName)
		if err != nil {
			return err
		}
		optionalMark := ""
		if !f.Required {
			optionalMark = "?"
		}
		valueType, err := r.tsValueType(f.Type, pascalName, f.WireName)
		if err != nil {
			return err
		}
		fmt.Fprintf(b, "  %s%s: %s | Computed<%s>;\n", idiomatic, optionalMark, valueType, valueType)
	}
	b.WriteString("}\n\n")

	// Attrs interface: every field, plain value types -- Computed<T>
	// wrapping happens once, generically, in the runtime's own Computed<T>
	// type (sdk/ts/runtime), not per-field here (docs/sdk.md: "resource()'s
	// return value's fields are Computed<T>", uniformly, not just the
	// schema-Computed ones -- see the runtime package's own doc comment
	// for why that's correct even for fields the program itself set).
	fmt.Fprintf(b, "export interface %sAttrs {\n", pascalName)
	for _, f := range rt.Fields {
		idiomatic, err := camelCase(f.WireName)
		if err != nil {
			return err
		}
		valueType, err := r.tsValueType(f.Type, pascalName, f.WireName)
		if err != nil {
			return err
		}
		fmt.Fprintf(b, "  %s: %s;\n", idiomatic, valueType)
	}
	b.WriteString("}\n\n")

	// The runtime descriptor -- the one thing resource() actually reads
	// at evaluation time (wireType for resources[].type, fields for
	// config-key -> wire-name mapping, recursively for nested objects).
	fmt.Fprintf(b, "export const %s: ResourceBinding<%sConfig, %sAttrs> = {\n", pascalName, pascalName, pascalName)
	fmt.Fprintf(b, "  wireType: %q,\n", rt.WireType)
	b.WriteString("  fields: {\n")
	for _, f := range rt.Fields {
		if !fieldIsSettable(f) {
			continue
		}
		idiomatic, err := camelCase(f.WireName)
		if err != nil {
			return err
		}
		spec, err := fieldSpecLiteral(f, 2)
		if err != nil {
			return err
		}
		fmt.Fprintf(b, "    %s: %s,\n", idiomatic, spec)
	}
	b.WriteString("  },\n")
	b.WriteString("};\n\n")

	return nil
}

// fieldIsSettable reports whether a field belongs in a Config interface
// at all -- true for Required or Optional fields (including a field that
// is BOTH Optional and Computed, a real, common schema shape: settable,
// but the provider fills it in if the program leaves it out), false only
// for a field that is Computed with neither Required nor Optional set
// (an output-only attribute like `id`/`arn` -- never legal as config
// input). A NestedBlock-derived field always has all three flags false
// (ir.go's own Field doc comment -- a real schema fact, not a gap in
// this package) and must NOT be excluded by that: `!f.Computed` alone
// already covers it (Computed is false for every nested block), which is
// why this is `Required || Optional || !Computed` rather than the
// simpler-looking `Required || Optional` that would silently drop every
// nested block from Config -- caught by TestGeneratedFile_NestedObjectBlock
// actually asserting on the rendered Config interface, not just the
// Attrs one.
func fieldIsSettable(f ir.Field) bool {
	return f.Required || f.Optional || !f.Computed
}

// resourceRenderer accumulates one resource type's own nested interface
// declarations (KindObject fields, at any depth) as tsValueType walks
// them, keyed by a deterministic, collision-free name derived from the
// full field path from the resource's own PascalCase name -- two
// different nested blocks can never collide since no two fields can
// share the same path.
type resourceRenderer struct {
	pascalName  string
	nestedDecls []string
	seen        map[string]bool
}

func (r *resourceRenderer) collectNestedInterfaces(f ir.Field, pathPrefix string) error {
	_, err := r.tsValueType(f.Type, pathPrefix, f.WireName)
	return err
}

// tsValueType returns the TS type text for one field's own TypeRef,
// recording a new nested interface declaration (once per unique path) as
// a side effect whenever it encounters a KindObject.
func (r *resourceRenderer) tsValueType(t ir.TypeRef, pathPrefix, wireName string) (string, error) {
	switch t.Kind {
	case ir.KindScalar:
		switch t.Scalar {
		case ir.ScalarString:
			return "string", nil
		case ir.ScalarNumber:
			return "number", nil
		case ir.ScalarBool:
			return "boolean", nil
		case ir.ScalarDynamic:
			return "unknown", nil
		default:
			return "", fmt.Errorf("field %q: unrecognized scalar kind %v", wireName, t.Scalar)
		}
	case ir.KindList, ir.KindSet:
		// JSON (and therefore intent/v1) has no Set shape distinct from
		// an array -- List and Set both render as T[], the same
		// collapse provider/ctyvalue.go's own JSON-level encoding
		// already makes (both decode as a JSON array).
		el, err := r.tsValueType(*t.Element, pathPrefix, wireName)
		if err != nil {
			return "", err
		}
		return el + "[]", nil
	case ir.KindMap:
		el, err := r.tsValueType(*t.Element, pathPrefix, wireName)
		if err != nil {
			return "", err
		}
		return "Record<string, " + el + ">", nil
	case ir.KindObject:
		fieldPascal, err := pascalCase(wireName)
		if err != nil {
			return "", err
		}
		name := pathPrefix + fieldPascal
		if r.seen == nil {
			r.seen = map[string]bool{}
		}
		if !r.seen[name] {
			r.seen[name] = true
			var body strings.Builder
			fmt.Fprintf(&body, "export interface %s {\n", name)
			for _, inner := range t.Object {
				innerIdiomatic, err := camelCase(inner.WireName)
				if err != nil {
					return "", err
				}
				innerType, err := r.tsValueType(inner.Type, name, inner.WireName)
				if err != nil {
					return "", err
				}
				fmt.Fprintf(&body, "  %s: %s;\n", innerIdiomatic, innerType)
			}
			body.WriteString("}\n")
			r.nestedDecls = append(r.nestedDecls, body.String())
		}
		return name, nil
	default:
		return "", fmt.Errorf("field %q: unrecognized type kind %v", wireName, t.Kind)
	}
}

// fieldSpecLiteral renders one settable field's own runtime FieldSpec
// literal (sdk/ts/runtime's own FieldSpec type: a plain wire-name string
// for a scalar or a list/set/map-of-scalar field -- no recursion needed,
// the runtime serializer passes those through as-is -- or an object
// literal naming wireName/kind/fields for anything that needs recursive
// wire-name mapping at evaluation time). A plain function, not a
// resourceRenderer method -- unlike tsValueType, it never needs to
// record a new nested interface declaration (that already happened, via
// renderResource's own collectNestedInterfaces pre-pass, before this is
// ever called).
func fieldSpecLiteral(f ir.Field, indent int) (string, error) {
	pad := strings.Repeat("  ", indent)
	innerPad := strings.Repeat("  ", indent+1)
	switch f.Type.Kind {
	case ir.KindScalar:
		return fmt.Sprintf("%q", f.WireName), nil
	case ir.KindList, ir.KindSet, ir.KindMap:
		if f.Type.Element.Kind != ir.KindObject {
			// A collection of scalars -- no per-element wire-name mapping
			// needed, same plain-string leaf as a bare scalar field.
			return fmt.Sprintf("%q", f.WireName), nil
		}
		kind := map[ir.TypeKind]string{ir.KindList: "list", ir.KindSet: "set", ir.KindMap: "map"}[f.Type.Kind]
		fieldsLit, err := objectFieldMapLiteral(f.Type.Element.Object, indent+1)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("{\n%swireName: %q,\n%skind: %q,\n%sfields: %s,\n%s}",
			innerPad, f.WireName, innerPad, kind, innerPad, fieldsLit, pad), nil
	case ir.KindObject:
		fieldsLit, err := objectFieldMapLiteral(f.Type.Object, indent+1)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("{\n%swireName: %q,\n%skind: %q,\n%sfields: %s,\n%s}",
			innerPad, f.WireName, innerPad, "object", innerPad, fieldsLit, pad), nil
	default:
		return "", fmt.Errorf("field %q: unrecognized type kind %v", f.WireName, f.Type.Kind)
	}
}

// objectFieldMapLiteral renders a FieldMap literal for one nested
// object's own fields -- every field of a nested object is "settable"
// from the config's own point of view (a program author writes the
// whole nested object literal; there's no separate Required/Optional
// gate at this level the way there is for a resource's own top-level
// Config, since NestedBlock-derived fields carry no such flags at all --
// ir.go's own Field doc comment).
func objectFieldMapLiteral(fields []ir.Field, indent int) (string, error) {
	pad := strings.Repeat("  ", indent)
	innerPad := strings.Repeat("  ", indent+1)
	var b strings.Builder
	b.WriteString("{\n")
	for _, f := range fields {
		idiomatic, err := camelCase(f.WireName)
		if err != nil {
			return "", err
		}
		spec, err := fieldSpecLiteral(f, indent+1)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "%s%s: %s,\n", innerPad, idiomatic, spec)
	}
	fmt.Fprintf(&b, "%s}", pad)
	return b.String(), nil
}

// pascalCase and camelCase both convert a provider wire name
// (snake_case, verbatim from a real schema -- e.g. "instance_class") into
// TypeScript's own idiomatic casing. Every real provider attribute name
// this codebase has seen (UBI-9's 51 AWS types, UBI-21's GCP types) is
// plain ASCII snake_case; both functions refuse anything else explicitly
// rather than silently producing a malformed identifier, matching this
// project's standing "never a best-effort coercion" rule (docs/sdk.md's
// own row 5).
func pascalCase(wireName string) (string, error) {
	parts, err := splitWireName(wireName)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	for _, p := range parts {
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String(), nil
}

func camelCase(wireName string) (string, error) {
	parts, err := splitWireName(wireName)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	for i, p := range parts {
		if i == 0 {
			b.WriteString(strings.ToLower(p[:1]))
			b.WriteString(p[1:])
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String(), nil
}

func splitWireName(wireName string) ([]string, error) {
	if wireName == "" {
		return nil, fmt.Errorf("empty wire name")
	}
	parts := strings.Split(wireName, "_")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if p == "" {
			continue // tolerate a leading/trailing/doubled underscore rather than hard-failing on it
		}
		for _, r := range p {
			if !(r >= 'a' && r <= 'z') && !(r >= '0' && r <= '9') {
				return nil, fmt.Errorf("wire name %q: unsupported character %q (only lowercase ascii + digits + underscore seen in any real provider schema this project has generated against)", wireName, r)
			}
		}
		out = append(out, p)
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("wire name %q: no identifier characters", wireName)
	}
	return out, nil
}
