package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// newInitCmd is UBI-19's config bootstrapper -- a new verb, no
// init-shaped command existed before this session
// (docs/architecture.md — Config defaults). Writes .ubx/config: a real,
// active value for every key the caller supplied a flag for, a
// commented-out example for everything else, so the file is immediately
// useful as its own documentation of what's possible.
func newInitCmd() *cobra.Command {
	var (
		dir             string
		force           bool
		stack           string
		source          string
		providerVersion string
		providerPath    string
		providerConfig  string
		githubRepo      string
		tfDir           string
	)

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Write a starter .ubx/config -- real values for whatever flags are given, commented examples for the rest",
		Long: `Write .ubx/config, the defaults file every ubx command reads (docs/architecture.md — Config defaults):
provider identity, provider configuration, default stack, GitHub repository, and .tf directory. Any flag you give
here is written as a real, active value; anything you don't is written as a commented-out example showing the
correct syntax. Refuses to overwrite an existing config unless --force is given.`,
		// init has no "finding" concept -- it either writes the file or it
		// doesn't (UBI-20 exit-code contract): 0 or 2 only.
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			if providerPath != "" && source != "" {
				return &ExitCodeError{Code: 2, Err: fmt.Errorf("init: --provider and --source are mutually exclusive")}
			}
			if source != "" && providerVersion == "" {
				return &ExitCodeError{Code: 2, Err: fmt.Errorf("init: --source requires --provider-version (explicit version pins only)")}
			}

			var providerConfigMap map[string]any
			if providerConfig != "" {
				if err := json.Unmarshal([]byte(providerConfig), &providerConfigMap); err != nil {
					return &ExitCodeError{Code: 2, Err: fmt.Errorf("init: --provider-config: %w", err)}
				}
			}

			path := filepath.Join(dir, ".ubx", "config")
			if info, err := os.Stat(path); err == nil {
				if info.IsDir() {
					return &ExitCodeError{Code: 2, Err: fmt.Errorf("init: %s is a directory", path)}
				}
				if !force {
					return &ExitCodeError{Code: 2, Err: fmt.Errorf("init: %s already exists (use --force to overwrite)", path)}
				}
			} else if !os.IsNotExist(err) {
				return &ExitCodeError{Code: 2, Err: fmt.Errorf("init: %w", err)}
			}

			content := renderConfigTemplate(configTemplateValues{
				Stack:           stack,
				Source:          source,
				ProviderVersion: providerVersion,
				ProviderPath:    providerPath,
				ProviderConfig:  providerConfigMap,
				GithubRepo:      githubRepo,
				TFDir:           tfDir,
			})

			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				return &ExitCodeError{Code: 2, Err: fmt.Errorf("init: %w", err)}
			}
			if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
				return &ExitCodeError{Code: 2, Err: fmt.Errorf("init: %w", err)}
			}

			fmt.Fprintf(cmd.OutOrStdout(), "wrote %s\n", path)
			return nil
		},
	}

	cmd.Flags().StringVar(&dir, "dir", ".", "directory to write .ubx/config into")
	cmd.Flags().BoolVar(&force, "force", false, "overwrite an existing .ubx/config")
	cmd.Flags().StringVar(&stack, "stack", "", "default stack name to write into the config")
	cmd.Flags().StringVar(&source, "source", "", "default provider source, e.g. hashicorp/aws (mutually exclusive with --provider; requires --provider-version)")
	cmd.Flags().StringVar(&providerVersion, "provider-version", "", "default provider version, e.g. 6.54.0 (used with --source)")
	cmd.Flags().StringVar(&providerPath, "provider", "", "default provider binary path (mutually exclusive with --source)")
	cmd.Flags().StringVar(&providerConfig, "provider-config", "", `default provider config, e.g. {"region":"us-east-1"}`)
	cmd.Flags().StringVar(&githubRepo, "github-repo", "", "default GitHub repository, e.g. acme/infra")
	cmd.Flags().StringVar(&tfDir, "tf-dir", "", "default .tf directory")

	return cmd
}

// configTemplateValues holds whatever real values ubx init was given --
// zero values mean "write a commented example instead."
type configTemplateValues struct {
	Stack           string
	Source          string
	ProviderVersion string
	ProviderPath    string
	ProviderConfig  map[string]any
	GithubRepo      string
	TFDir           string
}

// renderConfigTemplate builds .ubx/config's full text: a header comment,
// then one block per config key, real values where given, commented
// examples otherwise.
func renderConfigTemplate(v configTemplateValues) string {
	var b strings.Builder
	b.WriteString("# .ubx/config -- generated by `ubx init`.\n")
	b.WriteString("# CLI flags always override these; see https://github.com/Ubiquex/ubiquex-docs, cli/config.\n")
	b.WriteString("# Unknown keys warn, they don't fail -- safe to hand-edit.\n\n")

	// Root-level (non-table) keys MUST come before any [table] header --
	// in TOML, a bare key after a [table] section belongs to that table,
	// not the document root, regardless of blank lines between them. This
	// is a real ordering constraint, not a style choice: getting it
	// backwards (tables first) silently swallows stack/github_repo/tf_dir
	// into whatever table came last, and every value defined this way
	// reads back empty -- caught only by writing a real config file with
	// `ubx init` and decoding it back, not by inspecting the string
	// template by eye.
	b.WriteString("# Default stack for commands that need one (e.g. `ubx scan`, `ubx status --stack`).\n")
	if v.Stack != "" {
		fmt.Fprintf(&b, "stack = %q\n", v.Stack)
	} else {
		b.WriteString("# stack = \"payments\"\n")
	}
	b.WriteString("\n")

	b.WriteString("# Default GitHub repository for --from-merge / --verify-acceptance / --surface-as.\n")
	if v.GithubRepo != "" {
		fmt.Fprintf(&b, "github_repo = %q\n", v.GithubRepo)
	} else {
		b.WriteString("# github_repo = \"acme/infra\"\n")
	}
	b.WriteString("\n")

	b.WriteString("# Default .tf directory for --tf-dir (ubx writeback, ubx revert-plan, ubx scan --surface-as).\n")
	if v.TFDir != "" {
		fmt.Fprintf(&b, "tf_dir = %q\n", v.TFDir)
	} else {
		b.WriteString("# tf_dir = \"./terraform\"\n")
	}
	b.WriteString("\n")

	b.WriteString("# Provider identity: EITHER a local binary path, OR a registry source + explicit version.\n")
	b.WriteString("[provider]\n")
	switch {
	case v.ProviderPath != "":
		fmt.Fprintf(&b, "path = %q\n", v.ProviderPath)
		b.WriteString("# source = \"hashicorp/aws\"\n")
		b.WriteString("# version = \"6.54.0\"\n")
	case v.Source != "":
		b.WriteString("# path = \"/path/to/terraform-provider-aws\"\n")
		fmt.Fprintf(&b, "source = %q\n", v.Source)
		fmt.Fprintf(&b, "version = %q\n", v.ProviderVersion)
	default:
		b.WriteString("# path = \"/path/to/terraform-provider-aws\"\n")
		b.WriteString("# source = \"hashicorp/aws\"\n")
		b.WriteString("# version = \"6.54.0\"\n")
	}
	b.WriteString("\n")

	b.WriteString("# Provider configuration, e.g. the region a provider should read from.\n")
	b.WriteString("[provider_config]\n")
	if len(v.ProviderConfig) > 0 {
		keys := make([]string, 0, len(v.ProviderConfig))
		for k := range v.ProviderConfig {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&b, "%s = %s\n", k, tomlValue(v.ProviderConfig[k]))
		}
	} else {
		b.WriteString("# region = \"us-east-1\"\n")
	}

	return b.String()
}

// tomlValue renders a decoded-JSON value (string, float64, bool -- the
// only types encoding/json ever produces from a flat {"key":"value"}
// object) as a TOML literal.
func tomlValue(v any) string {
	switch t := v.(type) {
	case string:
		return fmt.Sprintf("%q", t)
	case bool:
		if t {
			return "true"
		}
		return "false"
	default:
		return fmt.Sprintf("%v", t)
	}
}
