package core

import (
	"context"
	"crypto/rand"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Salt returns this ledger's redaction salt (UBI-23, docs/architecture.md
// -- Secrets), generating and persisting one on first use. The salt is
// never part of any hashed/ledgered content and must never be committed
// -- see docs/schema.md's $redacted amendment for the honest recovery
// implication of losing it (it degrades redacted-value equality
// comparison across history -- an unchanged secret reports as drifted
// exactly once -- it never causes real material to leak and never causes
// a genuine change to go undetected).
//
// Two callers racing to generate the first salt at once is a real,
// if previously untested, case (UBI-32 Arc B, docs/ledgerstore-
// adversarial.md's row 11): WriteSaltIfAbsent's own create-only semantics
// mean exactly one caller's generated bytes win; the loser discards its
// own and reads the winner's back via ReadSalt instead, so every caller
// still returns a real, persisted, shared salt regardless of who
// actually wrote it.
func (l *Ledger) Salt() ([]byte, error) {
	ctx := context.Background()
	if b, found, err := l.store.ReadSalt(ctx); err != nil {
		return nil, fmt.Errorf("read ledger salt: %w", err)
	} else if found {
		return b, nil
	}

	salt := make([]byte, 32)
	if _, err := rand.Read(salt); err != nil {
		return nil, fmt.Errorf("generate ledger salt: %w", err)
	}
	err := l.store.WriteSaltIfAbsent(ctx, salt)
	switch {
	case err == nil:
		return salt, nil
	case errors.Is(err, ErrStoreObjectExists):
		b, found, readErr := l.store.ReadSalt(ctx)
		if readErr != nil {
			return nil, fmt.Errorf("read ledger salt (after losing the generation race): %w", readErr)
		}
		if !found {
			return nil, fmt.Errorf("generate ledger salt: %w", errors.New("salt reported as existing but not readable"))
		}
		return b, nil
	default:
		return nil, fmt.Errorf("generate ledger salt: %w", err)
	}
}

// ensureGitignored makes sure entry is listed in dir's .gitignore,
// creating a minimal one if none exists yet -- a safety net against an
// operator's own "git add -A" habit, not the only line of defense (the
// salt file is already 0600 and never itself becomes ledgered content
// regardless of whether it's gitignored). Git-directory-store-specific --
// see gitLedgerStore.WriteSaltIfAbsent, the only caller; a remote store's
// own salt object was never at risk of this in the first place.
func ensureGitignored(dir, entry string) error {
	path := filepath.Join(dir, ".gitignore")
	existing, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		return os.WriteFile(path, []byte(entry+"\n"), 0o644)
	}
	for _, line := range strings.Split(string(existing), "\n") {
		if strings.TrimSpace(line) == entry {
			return nil
		}
	}
	content := string(existing)
	if content != "" && !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	content += entry + "\n"
	return os.WriteFile(path, []byte(content), 0o644)
}
