// Package gotmpl is the Go template half of docs/sdk.md's own "Codegen
// design": ir.ResourceType (language-neutral, wire-name-only) -> idiomatic
// Go bindings. This is the only package in sdk/codegen that knows what
// "idiomatic Go" means -- exported PascalCase struct fields, a runtime
// FieldMap descriptor -- none of which leaks back into sdk/codegen/ir
// itself. Named gotmpl, not go (sdk/codegen/templates/go is the import
// path; go itself is a reserved word and cannot be a package identifier).
//
// Smaller output than sdk/codegen/templates/ts's own GeneratedFile:
// sdk/go/runtime's Computed has no static per-field type (Field(name)
// drills in dynamically, mirroring TS's Proxy without one), so there is
// no Go analog of TS's Attrs interface to render -- only a Config struct
// (plus nested object structs) and the runtime descriptor.
package gotmpl

import (
	"fmt"
	"sort"
	"strings"

	"github.com/ubiquex/ubiquex-cli/sdk/codegen/ir"
)

// GeneratedFile renders one Go source file covering every resource type
// declared by one provider source+version -- one file per provider
// source, mirroring sdk/codegen/templates/ts's own GeneratedFile
// exactly in that respect. types is sorted by WireType here, defensively,
// even if a caller already passed a sorted slice -- codegen output must
// never depend on caller-supplied ordering (determinism is a feature).
func GeneratedFile(pkg, source, version string, types []*ir.ResourceType) (string, error) {
	sorted := make([]*ir.ResourceType, len(types))
	copy(sorted, types)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].WireType < sorted[j].WireType })

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by `ubx sdk gen` from %s@%s. DO NOT EDIT.\n", source, version)
	b.WriteString("// This file is committed to git like any other reviewable generated code\n")
	b.WriteString("// (docs/sdk.md — \"ubx sdk gen: local, pinned, offline-after-generation\") --\n")
	b.WriteString("// re-run `ubx sdk gen` to regenerate after a provider version bump.\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import sdk \"github.com/ubiquex/ubx-sdk-go/runtime\"\n\n")
	fmt.Fprintf(&b, "var SourceProvenance = struct {\n\tSource  string\n\tVersion string\n}{Source: %q, Version: %q}\n\n", source, version)

	for _, rt := range sorted {
		if err := renderResource(&b, rt); err != nil {
			return "", fmt.Errorf("sdk/codegen/templates/go: %s: %w", rt.WireType, err)
		}
	}

	return b.String(), nil
}

// renderResource writes one resource type's full binding: nested object
// structs (as needed), the settable Config struct, and the runtime
// descriptor Resource() actually reads at evaluation time.
func renderResource(b *strings.Builder, rt *ir.ResourceType) error {
	pascalName, err := pascalCase(rt.WireType)
	if err != nil {
		return err
	}

	r := &resourceRenderer{pascalName: pascalName}
	for _, f := range rt.Fields {
		if !fieldIsSettable(f) {
			continue
		}
		if err := r.collectNestedStructs(f, pascalName); err != nil {
			return err
		}
	}
	for _, decl := range r.nestedDecls {
		b.WriteString(decl)
		b.WriteString("\n")
	}

	// Config struct: settable fields only (same fieldIsSettable rule
	// sdk/codegen/templates/ts uses -- a NestedBlock-derived field has
	// Required/Optional/Computed all false and must still be settable,
	// hence `!Computed` rather than `Required || Optional` alone).
	fmt.Fprintf(b, "type %sConfig struct {\n", pascalName)
	for _, f := range rt.Fields {
		if !fieldIsSettable(f) {
			continue
		}
		idiomatic, err := pascalCase(f.WireName)
		if err != nil {
			return err
		}
		fmt.Fprintf(b, "\t%s any\n", idiomatic)
	}
	b.WriteString("}\n\n")

	// The runtime descriptor.
	fmt.Fprintf(b, "var %s = sdk.ResourceBinding{\n", pascalName)
	fmt.Fprintf(b, "\tWireType: %q,\n", rt.WireType)
	b.WriteString("\tFields: sdk.FieldMap{\n")
	for _, f := range rt.Fields {
		if !fieldIsSettable(f) {
			continue
		}
		idiomatic, err := pascalCase(f.WireName)
		if err != nil {
			return err
		}
		spec, err := fieldSpecLiteral(f, 2)
		if err != nil {
			return err
		}
		fmt.Fprintf(b, "\t\t%q: %s,\n", idiomatic, spec)
	}
	b.WriteString("\t},\n")
	b.WriteString("}\n\n")

	return nil
}

// fieldIsSettable mirrors sdk/codegen/templates/ts's own function of the
// same name exactly -- see that package's doc comment for why this is
// `Required || Optional || !Computed` rather than the simpler-looking
// `Required || Optional`.
func fieldIsSettable(f ir.Field) bool {
	return f.Required || f.Optional || !f.Computed
}

// resourceRenderer accumulates one resource type's own nested Config
// struct declarations (KindObject fields, at any depth), keyed by a
// deterministic, collision-free name derived from the full field path
// from the resource's own PascalCase name.
type resourceRenderer struct {
	pascalName  string
	nestedDecls []string
	seen        map[string]bool
}

func (r *resourceRenderer) collectNestedStructs(f ir.Field, pathPrefix string) error {
	_, err := r.goFieldMeta(f.Type, pathPrefix, f.WireName)
	return err
}

// goFieldMeta records a new nested Config struct declaration (once per
// unique path) as a side effect whenever it encounters a KindObject.
// Unlike sdk/codegen/templates/ts's tsValueType, the return value itself
// is unused by callers (every Config field is typed any regardless of
// shape) -- this only exists to drive the nested-struct side effect
// walk.
func (r *resourceRenderer) goFieldMeta(t ir.TypeRef, pathPrefix, wireName string) (string, error) {
	switch t.Kind {
	case ir.KindScalar:
		return "", nil
	case ir.KindList, ir.KindSet, ir.KindMap:
		return r.goFieldMeta(*t.Element, pathPrefix, wireName)
	case ir.KindObject:
		fieldPascal, err := pascalCase(wireName)
		if err != nil {
			return "", err
		}
		name := pathPrefix + fieldPascal
		if r.seen == nil {
			r.seen = map[string]bool{}
		}
		if !r.seen[name] {
			r.seen[name] = true
			var body strings.Builder
			fmt.Fprintf(&body, "type %s struct {\n", name)
			for _, inner := range t.Object {
				innerIdiomatic, err := pascalCase(inner.WireName)
				if err != nil {
					return "", err
				}
				if _, err := r.goFieldMeta(inner.Type, name, inner.WireName); err != nil {
					return "", err
				}
				fmt.Fprintf(&body, "\t%s any\n", innerIdiomatic)
			}
			body.WriteString("}\n")
			r.nestedDecls = append(r.nestedDecls, body.String())
		}
		return name, nil
	default:
		return "", fmt.Errorf("field %q: unrecognized type kind %v", wireName, t.Kind)
	}
}

// fieldSpecLiteral renders one settable field's own runtime
// sdk.FieldSpec literal, mirroring sdk/codegen/templates/ts's own
// fieldSpecLiteral exactly (see that function's doc comment for the
// scalar-vs-object-vs-collection-of-object distinction).
func fieldSpecLiteral(f ir.Field, indent int) (string, error) {
	pad := strings.Repeat("\t", indent)
	innerPad := strings.Repeat("\t", indent+1)
	switch f.Type.Kind {
	case ir.KindScalar:
		return fmt.Sprintf("sdk.FieldSpec{WireName: %q}", f.WireName), nil
	case ir.KindList, ir.KindSet, ir.KindMap:
		if f.Type.Element.Kind != ir.KindObject {
			return fmt.Sprintf("sdk.FieldSpec{WireName: %q}", f.WireName), nil
		}
		kind := map[ir.TypeKind]string{ir.KindList: "list", ir.KindSet: "set", ir.KindMap: "map"}[f.Type.Kind]
		fieldsLit, err := objectFieldMapLiteral(f.Type.Element.Object, indent+1)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("sdk.FieldSpec{\n%sWireName: %q,\n%sKind: %q,\n%sFields: %s,\n%s}",
			innerPad, f.WireName, innerPad, kind, innerPad, fieldsLit, pad), nil
	case ir.KindObject:
		fieldsLit, err := objectFieldMapLiteral(f.Type.Object, indent+1)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("sdk.FieldSpec{\n%sWireName: %q,\n%sKind: %q,\n%sFields: %s,\n%s}",
			innerPad, f.WireName, innerPad, "object", innerPad, fieldsLit, pad), nil
	default:
		return "", fmt.Errorf("field %q: unrecognized type kind %v", f.WireName, f.Type.Kind)
	}
}

// objectFieldMapLiteral renders an sdk.FieldMap literal for one nested
// object's own fields -- every field of a nested object is "settable"
// from the config's own point of view (mirrors
// sdk/codegen/templates/ts's own objectFieldMapLiteral).
func objectFieldMapLiteral(fields []ir.Field, indent int) (string, error) {
	pad := strings.Repeat("\t", indent)
	innerPad := strings.Repeat("\t", indent+1)
	var b strings.Builder
	b.WriteString("sdk.FieldMap{\n")
	for _, f := range fields {
		idiomatic, err := pascalCase(f.WireName)
		if err != nil {
			return "", err
		}
		spec, err := fieldSpecLiteral(f, indent+1)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "%s%q: %s,\n", innerPad, idiomatic, spec)
	}
	fmt.Fprintf(&b, "%s}", pad)
	return b.String(), nil
}

// pascalCase converts a provider wire name (snake_case, verbatim from a
// real schema -- e.g. "instance_class") into Go's own idiomatic exported
// identifier casing ("InstanceClass"). Mirrors
// sdk/codegen/templates/ts's own pascalCase/splitWireName exactly,
// including the "never a best-effort coercion" refusal on anything
// outside plain ASCII snake_case (docs/sdk.md's own row 5).
func pascalCase(wireName string) (string, error) {
	parts, err := splitWireName(wireName)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	for _, p := range parts {
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String(), nil
}

func splitWireName(wireName string) ([]string, error) {
	if wireName == "" {
		return nil, fmt.Errorf("empty wire name")
	}
	parts := strings.Split(wireName, "_")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if p == "" {
			continue // tolerate a leading/trailing/doubled underscore rather than hard-failing on it
		}
		for _, r := range p {
			if !(r >= 'a' && r <= 'z') && !(r >= '0' && r <= '9') {
				return nil, fmt.Errorf("wire name %q: unsupported character %q (only lowercase ascii + digits + underscore seen in any real provider schema this project has generated against)", wireName, r)
			}
		}
		out = append(out, p)
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("wire name %q: no identifier characters", wireName)
	}
	return out, nil
}
