// Package mdrender is UBI-86's own markdown "current state" render: the
// human-readable prose counterpart to diagram.Emit's own D2 render,
// sharing the identical diagram.Walk read (Fleet/FoldState/creating-
// proposal) -- never a second ledger walk, never a second blueprint-
// grouping mechanism. Named for its own role, rendering markdown, not
// for Markdown-the-format's own external name beyond that (CLAUDE.md's
// package-naming convention) -- this is a RENDER, not a new medium
// (UBI-86's own framing): there is no parse direction here at all, only
// FoldState -> readable prose, the literal converse of nothing (unlike
// the diagram medium, which has both directions).
//
// The design principle every session touching this package must keep
// stated plainly, in the rendered document's own header and here:
// this document is CURRENT STATE, generated, and it is NEVER
// hand-edited. The authoring document(s) that created these resources
// (an SDK program, a diagram, an md draft) remain separate, historical
// evidence of individual decisions -- they are not meant to stay
// current and should not be hand-edited to match reality. This render
// answers "what exists now"; `ubx why`/`ubx blame` remain the answer to
// "how did it get this way." Neither replaces the other.
package mdrender

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/ubiquex/ubiquex/core"
	"github.com/ubiquex/ubiquex/diagram"
)

// Emit walks stack's own live resources in l (diagram.Walk -- the exact
// same read diagram.Emit's D2 rendering uses) and produces a readable
// markdown document. Deterministic: two Emit calls against an unchanged
// ledger produce byte-identical output (every map iterated here is
// sorted first, nothing here reads a clock or random source) -- the
// property `ubx render --md --check` needs, reusing render's own
// --check byte-compare plumbing (cli/render.go) unchanged.
func Emit(l *core.Ledger, stack string) ([]byte, error) {
	resources, err := diagram.Walk(l, stack)
	if err != nil {
		return nil, fmt.Errorf("mdrender: %w", err)
	}

	var b bytes.Buffer
	writeHeader(&b, stack)

	if len(resources) == 0 {
		b.WriteString("_No live resources._\n")
		return b.Bytes(), nil
	}

	// Grouping (UBI-86 item 2): blueprint-sourced resources group under
	// their own heading first, reusing the identical grouping basis
	// diagram.Emit's own dashed D2 container uses (diagram.Resource.
	// BlueprintRef, real resolved-time truth read off each resource's
	// own creating proposal -- never a guessed structure, matching
	// docs/blueprint.md's own "not a synthetic container, real resolved-
	// time truth" reasoning for the D2 side). Within each group
	// (including the top-level ungrouped one), resources sub-group by
	// TYPE, alphabetically -- the simpler of the two options this
	// ticket named ("by type or dependency structure"): a dependency-
	// structure TREE reads well in a diagram's own 2D layout, but in a
	// strictly linear document it degrades to exactly the information a
	// "depends on: ..." line under each resource already carries, so
	// the added structural complexity of a tree wasn't worth it here --
	// see docs/render-md.md for the full account of this choice.
	groups, order := groupByBlueprint(resources)
	for i, ref := range order {
		if i > 0 {
			b.WriteString("\n")
		}
		if ref != "" {
			fmt.Fprintf(&b, "## Blueprint: %s\n\n", diagram.ShortBlueprintRef(ref))
		} else if len(order) > 1 {
			// A heading for the ungrouped bucket is only worth printing
			// when there's a blueprint group to distinguish it FROM --
			// a stack with zero blueprint calls (the common case) renders
			// with no redundant top-level "## Resources" heading at all.
			b.WriteString("## Resources\n\n")
		}
		writeResourceGroup(&b, groups[ref])
	}

	return b.Bytes(), nil
}

func writeHeader(b *bytes.Buffer, stack string) {
	fmt.Fprintf(b, "# %s — current state\n\n", stack)
	b.WriteString("_Generated by `ubx render --md` from the ledger. " +
		"This is CURRENT STATE -- what exists right now -- never hand-edited; " +
		"edit the authoring source (SDK/diagram/md) and re-resolve/ship instead. " +
		"The authoring document(s) that created these resources remain separate, " +
		"historical evidence of individual decisions, and are not meant to stay " +
		"current. See `ubx why`/`ubx blame` for how a resource got this way._\n\n")
}

// groupByBlueprint partitions resources by BlueprintRef (""  for
// ungrouped) and returns a deterministic render order: the ungrouped
// bucket first (if non-empty), then every real blueprint ref sorted --
// matching diagram.Emit's own "ungrouped resources render exactly as
// before, unchanged for a stack with zero blueprint calls" invariant
// (the ungrouped bucket, when it's the ONLY bucket, renders with no
// extra heading at all -- see Emit above).
func groupByBlueprint(resources []diagram.Resource) (map[string][]diagram.Resource, []string) {
	groups := map[string][]diagram.Resource{}
	for _, r := range resources {
		groups[r.BlueprintRef] = append(groups[r.BlueprintRef], r)
	}
	var refs []string
	for ref := range groups {
		if ref == "" {
			continue
		}
		refs = append(refs, ref)
	}
	sort.Strings(refs)

	order := make([]string, 0, len(refs)+1)
	if _, ok := groups[""]; ok {
		order = append(order, "")
	}
	order = append(order, refs...)
	return groups, order
}

// writeResourceGroup sub-groups group by resource type, alphabetically,
// then renders each resource under its own type heading.
func writeResourceGroup(b *bytes.Buffer, group []diagram.Resource) {
	byType := map[string][]diagram.Resource{}
	var types []string
	for _, r := range group {
		if _, ok := byType[r.Addr.Type]; !ok {
			types = append(types, r.Addr.Type)
		}
		byType[r.Addr.Type] = append(byType[r.Addr.Type], r)
	}
	sort.Strings(types)

	for _, t := range types {
		rs := byType[t]
		sort.Slice(rs, func(i, j int) bool { return rs[i].Addr.Name < rs[j].Addr.Name })
		fmt.Fprintf(b, "### %s\n\n", t)
		for _, r := range rs {
			writeResource(b, r)
		}
	}
}

// writeResource renders one resource: a heading naming it, its own
// live attributes (readable, formatted, never a raw JSON dump -- see
// writeAttrLines), then its dependency edges.
func writeResource(b *bytes.Buffer, r diagram.Resource) {
	fmt.Fprintf(b, "#### %s\n\n", r.Addr.Name)

	keys := make([]string, 0, len(r.Attrs))
	for k := range r.Attrs {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		writeAttrLines(b, "", k, r.Attrs[k])
	}

	if len(r.DependsOn) > 0 {
		deps := append([]string(nil), r.DependsOn...)
		sort.Strings(deps)
		fmt.Fprintf(b, "- depends on: %s\n", strings.Join(backtickEach(deps), ", "))
	}
	if len(r.CrossPins) > 0 {
		pins := make([]string, len(r.CrossPins))
		for i, p := range r.CrossPins {
			pins[i] = p.Resource
		}
		sort.Strings(pins)
		fmt.Fprintf(b, "- references (cross-stack): %s\n", strings.Join(backtickEach(pins), ", "))
	}
	b.WriteString("\n")
}

// writeAttrLines writes name's own value as one bullet at indent depth,
// recursing into a nested object/array as further-indented sub-bullets
// instead of ever squeezing a nested value into one JSON blob --
// "live attributes in readable formatted form (never raw JSON dumps)"
// (UBI-86's own explicit requirement), taken literally: a nested
// attribute value (a tags map, an IAM policy document decoded from its
// own JSON-string attribute -- though a STRING-typed policy attribute
// itself still renders as a plain string here, one level up; only a
// genuinely object/array-shaped attribute value recurses) renders as
// further bullets, never a compact inline JSON dump.
//
// A $redacted marker (core.IsRedactedValue, UBI-23) is checked BEFORE
// decoding into interface{} at every recursion level, not just the top
// one -- the same "(redacted)" wording cli/revertplan.go's own
// rawOrAbsent already established for why/revert-plan output, kept
// consistent here rather than inventing a second phrase for the
// identical fact.
//
// Deliberately does NOT attempt to mark an attribute "(computed)": that
// distinction is schema metadata (provider.Block.Attributes[i].Computed),
// not a property of the state JSON itself, and Walk's own read is
// provider-free by design (matching diagram.Emit's own "no provider
// needed, pure ledger read" posture) -- adding it would mean launching a
// provider just to annotate a render, a real scope expansion this
// ticket's own success bar doesn't ask for. Named here, not silently
// dropped -- see docs/render-md.md.
func writeAttrLines(b *bytes.Buffer, indent, name string, raw json.RawMessage) {
	if core.IsRedactedValue(raw) {
		fmt.Fprintf(b, "%s- `%s`: (redacted)\n", indent, name)
		return
	}

	var v interface{}
	if err := json.Unmarshal(raw, &v); err != nil {
		fmt.Fprintf(b, "%s- `%s`: %s\n", indent, name, string(raw))
		return
	}

	switch t := v.(type) {
	case map[string]interface{}:
		if len(t) == 0 {
			fmt.Fprintf(b, "%s- `%s`: (empty)\n", indent, name)
			return
		}
		fmt.Fprintf(b, "%s- `%s`:\n", indent, name)
		for _, k := range sortedKeys(t) {
			child, _ := json.Marshal(t[k])
			writeAttrLines(b, indent+"  ", k, child)
		}
	case []interface{}:
		if len(t) == 0 {
			fmt.Fprintf(b, "%s- `%s`: (empty list)\n", indent, name)
			return
		}
		fmt.Fprintf(b, "%s- `%s`:\n", indent, name)
		for i, item := range t {
			child, _ := json.Marshal(item)
			writeAttrLines(b, indent+"  ", fmt.Sprintf("[%d]", i), child)
		}
	case string:
		fmt.Fprintf(b, "%s- `%s`: %s\n", indent, name, t)
	case nil:
		fmt.Fprintf(b, "%s- `%s`: null\n", indent, name)
	default:
		fmt.Fprintf(b, "%s- `%s`: %v\n", indent, name, t)
	}
}

func sortedKeys(m map[string]interface{}) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func backtickEach(ss []string) []string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = "`" + s + "`"
	}
	return out
}
