// Package pytmpl is the Python template half of docs/sdk.md's own
// "Codegen design": ir.ResourceType (language-neutral, wire-name-only) ->
// idiomatic Python bindings. This is the only package in sdk/codegen
// that knows what "idiomatic Python" means -- @dataclass Config classes,
// a runtime FieldMap descriptor -- none of which leaks back into
// sdk/codegen/ir itself.
//
// Smaller field-naming problem than TS (camelCase) or Go (PascalCase):
// every real provider wire name this project has generated against is
// already lowercase-with-underscores -- already a valid, idiomatic
// Python identifier verbatim. The only real work here is guarding
// against a wire name that collides with a Python keyword (rare, but
// real -- e.g. a field literally named "class" or "in"), handled the
// same way generated protobuf/thrift Python bindings conventionally do:
// a trailing underscore.
package pytmpl

import (
	"fmt"
	"sort"
	"strings"

	"github.com/ubiquex/ubiquex/sdk/codegen/ir"
)

// GeneratedFile renders one Python module covering every resource type
// declared by one provider source+version -- one file per provider
// source, mirroring the TS/Go templates' own GeneratedFile exactly in
// that respect. types is sorted by WireType here, defensively, even if a
// caller already passed a sorted slice -- codegen output must never
// depend on caller-supplied ordering.
func GeneratedFile(source, version string, types []*ir.ResourceType) (string, error) {
	sorted := make([]*ir.ResourceType, len(types))
	copy(sorted, types)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].WireType < sorted[j].WireType })

	var b strings.Builder
	fmt.Fprintf(&b, "# Code generated by `ubx sdk gen` from %s@%s. DO NOT EDIT.\n", source, version)
	b.WriteString("# This file is committed to git like any other reviewable generated code\n")
	b.WriteString("# (docs/sdk.md — \"ubx sdk gen: local, pinned, offline-after-generation\") --\n")
	b.WriteString("# re-run `ubx sdk gen` to regenerate after a provider version bump.\n")
	b.WriteString("from __future__ import annotations\n\n")
	b.WriteString("import dataclasses\n")
	b.WriteString("from typing import Any\n\n")
	b.WriteString("import ubx_sdk as sdk\n\n")
	fmt.Fprintf(&b, "SOURCE_PROVENANCE = {%q: %q, %q: %q}\n\n", "source", source, "version", version)

	for _, rt := range sorted {
		if err := renderResource(&b, rt); err != nil {
			return "", fmt.Errorf("sdk/codegen/templates/py: %s: %w", rt.WireType, err)
		}
	}

	return b.String(), nil
}

// renderResource writes one resource type's full binding: nested object
// dataclasses (as needed), the settable Config dataclass, and the
// runtime descriptor resource() actually reads at evaluation time.
func renderResource(b *strings.Builder, rt *ir.ResourceType) error {
	pascalName, err := pascalCase(rt.WireType)
	if err != nil {
		return err
	}

	r := &resourceRenderer{pascalName: pascalName}
	for _, f := range rt.Fields {
		if !fieldIsSettable(f) {
			continue
		}
		if err := r.collectNestedDataclasses(f, pascalName); err != nil {
			return err
		}
	}
	for _, decl := range r.nestedDecls {
		b.WriteString(decl)
		b.WriteString("\n")
	}

	// Config dataclass: settable fields only (same fieldIsSettable rule
	// sdk/codegen/templates/ts and .../go use -- a NestedBlock-derived
	// field has Required/Optional/Computed all false and must still be
	// settable, hence `!Computed` rather than `Required || Optional`
	// alone).
	fmt.Fprintf(b, "@dataclasses.dataclass\nclass %sConfig:\n", pascalName)
	var anyField bool
	for _, f := range rt.Fields {
		if !fieldIsSettable(f) {
			continue
		}
		idiomatic, err := pythonIdentifier(f.WireName)
		if err != nil {
			return err
		}
		anyField = true
		fmt.Fprintf(b, "    %s: Any = None\n", idiomatic)
	}
	if !anyField {
		b.WriteString("    pass\n")
	}
	b.WriteString("\n")

	// The runtime descriptor.
	fmt.Fprintf(b, "%s = sdk.ResourceBinding(\n", pascalName)
	fmt.Fprintf(b, "    wire_type=%q,\n", rt.WireType)
	b.WriteString("    fields={\n")
	for _, f := range rt.Fields {
		if !fieldIsSettable(f) {
			continue
		}
		idiomatic, err := pythonIdentifier(f.WireName)
		if err != nil {
			return err
		}
		spec, err := fieldSpecLiteral(f, 2)
		if err != nil {
			return err
		}
		fmt.Fprintf(b, "        %q: %s,\n", idiomatic, spec)
	}
	b.WriteString("    },\n")
	b.WriteString(")\n\n")

	return nil
}

// fieldIsSettable mirrors sdk/codegen/templates/ts and .../go's own
// function of the same name exactly.
func fieldIsSettable(f ir.Field) bool {
	return f.Required || f.Optional || !f.Computed
}

// resourceRenderer accumulates one resource type's own nested Config
// dataclass declarations (KindObject fields, at any depth), keyed by a
// deterministic, collision-free name derived from the full field path
// from the resource's own PascalCase name (used only for the generated
// CLASS name -- Python class names are conventionally PascalCase even
// though field/module names are snake_case).
type resourceRenderer struct {
	pascalName  string
	nestedDecls []string
	seen        map[string]bool
}

func (r *resourceRenderer) collectNestedDataclasses(f ir.Field, pathPrefix string) error {
	_, err := r.pyFieldMeta(f.Type, pathPrefix, f.WireName)
	return err
}

// pyFieldMeta records a new nested Config dataclass declaration (once
// per unique path) as a side effect whenever it encounters a KindObject.
// The return value itself is unused by callers (every Config field is
// typed Any regardless of shape) -- this only exists to drive the
// nested-dataclass side effect walk, mirroring
// sdk/codegen/templates/go's own goFieldMeta.
func (r *resourceRenderer) pyFieldMeta(t ir.TypeRef, pathPrefix, wireName string) (string, error) {
	switch t.Kind {
	case ir.KindScalar:
		return "", nil
	case ir.KindList, ir.KindSet, ir.KindMap:
		return r.pyFieldMeta(*t.Element, pathPrefix, wireName)
	case ir.KindObject:
		fieldPascal, err := pascalCase(wireName)
		if err != nil {
			return "", err
		}
		name := pathPrefix + fieldPascal
		if r.seen == nil {
			r.seen = map[string]bool{}
		}
		if !r.seen[name] {
			r.seen[name] = true
			var body strings.Builder
			fmt.Fprintf(&body, "@dataclasses.dataclass\nclass %s:\n", name)
			var anyField bool
			for _, inner := range t.Object {
				innerIdiomatic, err := pythonIdentifier(inner.WireName)
				if err != nil {
					return "", err
				}
				if _, err := r.pyFieldMeta(inner.Type, name, inner.WireName); err != nil {
					return "", err
				}
				anyField = true
				fmt.Fprintf(&body, "    %s: Any = None\n", innerIdiomatic)
			}
			if !anyField {
				body.WriteString("    pass\n")
			}
			r.nestedDecls = append(r.nestedDecls, body.String())
		}
		return name, nil
	default:
		return "", fmt.Errorf("field %q: unrecognized type kind %v", wireName, t.Kind)
	}
}

// fieldSpecLiteral renders one settable field's own runtime
// sdk.FieldSpec(...) call literal, mirroring
// sdk/codegen/templates/go's own fieldSpecLiteral exactly (see that
// function's doc comment for the scalar-vs-object-vs-collection-of-
// object distinction).
func fieldSpecLiteral(f ir.Field, indent int) (string, error) {
	pad := strings.Repeat("    ", indent)
	innerPad := strings.Repeat("    ", indent+1)
	switch f.Type.Kind {
	case ir.KindScalar:
		return fmt.Sprintf("sdk.FieldSpec(wire_name=%q)", f.WireName), nil
	case ir.KindList, ir.KindSet, ir.KindMap:
		if f.Type.Element.Kind != ir.KindObject {
			return fmt.Sprintf("sdk.FieldSpec(wire_name=%q)", f.WireName), nil
		}
		kind := map[ir.TypeKind]string{ir.KindList: "list", ir.KindSet: "set", ir.KindMap: "map"}[f.Type.Kind]
		fieldsLit, err := objectFieldMapLiteral(f.Type.Element.Object, indent+1)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("sdk.FieldSpec(\n%swire_name=%q,\n%skind=%q,\n%sfields=%s,\n%s)",
			innerPad, f.WireName, innerPad, kind, innerPad, fieldsLit, pad), nil
	case ir.KindObject:
		fieldsLit, err := objectFieldMapLiteral(f.Type.Object, indent+1)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("sdk.FieldSpec(\n%swire_name=%q,\n%skind=%q,\n%sfields=%s,\n%s)",
			innerPad, f.WireName, innerPad, "object", innerPad, fieldsLit, pad), nil
	default:
		return "", fmt.Errorf("field %q: unrecognized type kind %v", f.WireName, f.Type.Kind)
	}
}

// objectFieldMapLiteral renders a FieldMap dict literal for one nested
// object's own fields -- every field of a nested object is "settable"
// from the config's own point of view (mirrors
// sdk/codegen/templates/go's own objectFieldMapLiteral).
func objectFieldMapLiteral(fields []ir.Field, indent int) (string, error) {
	pad := strings.Repeat("    ", indent)
	innerPad := strings.Repeat("    ", indent+1)
	var b strings.Builder
	b.WriteString("{\n")
	for _, f := range fields {
		idiomatic, err := pythonIdentifier(f.WireName)
		if err != nil {
			return "", err
		}
		spec, err := fieldSpecLiteral(f, indent+1)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "%s%q: %s,\n", innerPad, idiomatic, spec)
	}
	fmt.Fprintf(&b, "%s}", pad)
	return b.String(), nil
}

// pythonIdentifier turns a provider wire name (snake_case, verbatim from
// a real schema -- e.g. "instance_class") into a Config dataclass's own
// field name. Unlike TS's camelCase or Go's PascalCase conversion, this
// is the identity function for every real wire name this project has
// ever generated against -- already lowercase-with-underscores, already
// a valid Python identifier -- except for the one real edge case a wire
// name could hit that TS/Go never need to guard against: colliding with
// a Python keyword (e.g. a field literally named "class" or "in"),
// resolved with a trailing underscore, the same convention generated
// protobuf/thrift Python bindings already use.
func pythonIdentifier(wireName string) (string, error) {
	parts, err := splitWireName(wireName)
	if err != nil {
		return "", err
	}
	joined := strings.Join(parts, "_")
	if pythonKeywords[joined] {
		return joined + "_", nil
	}
	return joined, nil
}

// pascalCase converts a provider wire name into a Python class-name
// identifier (PascalCase, the conventional Python class-naming style,
// PEP 8) -- used only for generated dataclass/ResourceBinding names,
// never for field names (see pythonIdentifier, above).
func pascalCase(wireName string) (string, error) {
	parts, err := splitWireName(wireName)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	for _, p := range parts {
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String(), nil
}

func splitWireName(wireName string) ([]string, error) {
	if wireName == "" {
		return nil, fmt.Errorf("empty wire name")
	}
	parts := strings.Split(wireName, "_")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if p == "" {
			continue // tolerate a leading/trailing/doubled underscore rather than hard-failing on it
		}
		for _, r := range p {
			if !(r >= 'a' && r <= 'z') && !(r >= '0' && r <= '9') {
				return nil, fmt.Errorf("wire name %q: unsupported character %q (only lowercase ascii + digits + underscore seen in any real provider schema this project has generated against)", wireName, r)
			}
		}
		out = append(out, p)
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("wire name %q: no identifier characters", wireName)
	}
	return out, nil
}

// pythonKeywords is the lowercase-only subset of Python 3's reserved-word
// set (keyword.kwlist) that a real wire name could ever actually collide
// with -- splitWireName only ever accepts lowercase ascii, so the
// capitalized reserved words (False/None/True) can never match a real
// wire name and are omitted rather than listed misleadingly.
var pythonKeywords = map[string]bool{
	"and": true, "as": true, "assert": true, "async": true, "await": true,
	"break": true, "class": true, "continue": true, "def": true, "del": true,
	"elif": true, "else": true, "except": true, "finally": true, "for": true,
	"from": true, "global": true, "if": true, "import": true, "in": true,
	"is": true, "lambda": true, "nonlocal": true, "not": true, "or": true,
	"pass": true, "raise": true, "return": true, "try": true, "while": true,
	"with": true, "yield": true,
}
