// Command gentool generates core/lookuphints' shipped table from
// conformance.Registry's LookupHint field (UBI-20 workstream 3,
// docs/architecture.md — Teaching errors: promote the lookup data, not the
// package). Invoked via the //go:generate directive in
// conformance/registry.go; never run automatically, and never imported by
// anything else -- a generator is dev-time tooling, same category as
// conformance itself.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"

	"github.com/ubiquex/ubiquex/conformance"
)

func main() {
	out := flag.String("out", "", "output path for the generated Go source")
	flag.Parse()
	if *out == "" {
		fmt.Fprintln(os.Stderr, "gentool: -out is required")
		os.Exit(2)
	}

	type entry struct {
		source string
		typ    string
		extra  []string
	}
	var entries []entry
	for _, spec := range conformance.Registry {
		if len(spec.LookupHint) == 0 {
			continue
		}
		entries = append(entries, entry{source: spec.Source, typ: spec.Type, extra: spec.LookupHint})
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].source != entries[j].source {
			return entries[i].source < entries[j].source
		}
		return entries[i].typ < entries[j].typ
	})

	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by conformance/gentool from conformance.Registry's")
	fmt.Fprintln(&b, "// LookupHint field. DO NOT EDIT by hand -- edit the Registry entry's")
	fmt.Fprintln(&b, "// LookupHint instead and re-run `go generate ./conformance/...`.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// Package lookuphints is UBI-20 workstream 3's shipped teaching-error")
	fmt.Fprintln(&b, "// data: for a handful of resource types, the natural-key attribute")
	fmt.Fprintln(&b, "// name(s) (Terraform's own attribute, e.g. \"bucket\"/\"name\") that read")
	fmt.Fprintln(&b, "// back null when supplied alone, without \"id\".")
	fmt.Fprintln(&b, "//")
	fmt.Fprintln(&b, "// This used to cite \"cli/lookup.mdx in ubiquex-docs\" for a human-readable")
	fmt.Fprintln(&b, "// table. No such page exists, in the live docs site or in the retired")
	fmt.Fprintln(&b, "// one that sentence named. Removed rather than repointed: the live")
	fmt.Fprintln(&b, "// equivalent, docs.ubiquex.io/cli-reference/scan, documents the flag but")
	fmt.Fprintln(&b, "// publishes no per-type table, and citing it as though it did would")
	fmt.Fprintln(&b, "// repeat the same mistake more quietly (UBI-270).")
	fmt.Fprintln(&b, "//")
	fmt.Fprintln(&b, "// UBI-270 also narrowed what this package is FOR. A dynamic provider's")
	fmt.Fprintln(&b, "// schema snapshot publishes its own identity map, covering every resource")
	fmt.Fprintln(&b, "// type it has, and core.lookupHintText prefers it. This table still runs")
	fmt.Fprintln(&b, "// for a provider with no snapshot to publish one, which is every")
	fmt.Fprintln(&b, "// Terraform-registry provider, where its few empirically-verified entries")
	fmt.Fprintln(&b, "// remain the only thing anyone knows.")
	fmt.Fprintln(&b, "//")
	fmt.Fprintln(&b, "// Keyed by (provider source, type), not type alone (UBI-21,")
	fmt.Fprintln(&b, "// docs/architecture.md -- GCP support), the same reasoning")
	fmt.Fprintln(&b, "// conformance.Registry's own keying follows. This package has zero")
	fmt.Fprintln(&b, "// runtime dependency on conformance -- that package is explicitly")
	fmt.Fprintln(&b, "// test-only tooling (see its own doc comment), never imported by shipped")
	fmt.Fprintln(&b, "// product code. Promoting the DATA into a small generated table here,")
	fmt.Fprintln(&b, "// rather than importing the package directly, keeps that boundary intact")
	fmt.Fprintln(&b, "// while still avoiding a hand-duplicated copy that could drift from what")
	fmt.Fprintln(&b, "// conformance actually verified.")
	fmt.Fprintln(&b, "package lookuphints")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// hints maps a provider source to its resource types' natural-key")
	fmt.Fprintln(&b, "// attribute(s) that read back null when supplied alone in --lookup,")
	fmt.Fprintln(&b, "// without \"id\".")
	fmt.Fprintln(&b, "var hints = map[string]map[string][]string{}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "func init() {")
	prevSource := ""
	for _, e := range entries {
		if e.source != prevSource {
			fmt.Fprintf(&b, "\thints[%q] = map[string][]string{}\n", e.source)
			prevSource = e.source
		}
		fmt.Fprintf(&b, "\thints[%q][%q] = []string{", e.source, e.typ)
		for i, attr := range e.extra {
			if i > 0 {
				fmt.Fprint(&b, ", ")
			}
			fmt.Fprintf(&b, "%q", attr)
		}
		fmt.Fprintln(&b, "}")
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// For returns resourceType's natural-key attribute(s), under the given")
	fmt.Fprintln(&b, "// provider source, known to read back null when supplied alone in")
	fmt.Fprintln(&b, "// --lookup (without \"id\"), and whether any are known at all. A false ok")
	fmt.Fprintln(&b, "// means \"id\" alone is the verified shape, or that source is unrecognized")
	fmt.Fprintln(&b, "// -- not that this type was never checked. \"Verified\" means checked live")
	fmt.Fprintln(&b, "// against the real provider (conformance/lookuphints_live_test.go), not")
	fmt.Fprintln(&b, "// inferred from documentation. An empty source (e.g. a scan via a raw")
	fmt.Fprintln(&b, "// --provider path, with no known registry source) always returns false --")
	fmt.Fprintln(&b, "// see core.ScanRequest.ProviderSource's own doc comment for why that's an")
	fmt.Fprintln(&b, "// accepted narrowing, not a bug.")
	fmt.Fprintln(&b, "func For(source, resourceType string) ([]string, bool) {")
	fmt.Fprintln(&b, "\th, ok := hints[source][resourceType]")
	fmt.Fprintln(&b, "\treturn h, ok")
	fmt.Fprintln(&b, "}")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "gentool: formatting generated source: %v\n", err)
		os.Exit(2)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gentool: %v\n", err)
		os.Exit(2)
	}
}
