// Command gentool generates core/lookuphints' shipped table from
// conformance.Registry's LookupHint field (UBI-20 workstream 3,
// docs/architecture.md — Teaching errors: promote the lookup data, not the
// package). Invoked via the //go:generate directive in
// conformance/registry.go; never run automatically, and never imported by
// anything else -- a generator is dev-time tooling, same category as
// conformance itself.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"

	"github.com/ubiquex/ubiquex-cli/conformance"
)

func main() {
	out := flag.String("out", "", "output path for the generated Go source")
	flag.Parse()
	if *out == "" {
		fmt.Fprintln(os.Stderr, "gentool: -out is required")
		os.Exit(2)
	}

	type entry struct {
		typ   string
		extra []string
	}
	var entries []entry
	for _, spec := range conformance.Registry {
		if len(spec.LookupHint) == 0 {
			continue
		}
		entries = append(entries, entry{typ: spec.Type, extra: spec.LookupHint})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].typ < entries[j].typ })

	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by conformance/gentool from conformance.Registry's")
	fmt.Fprintln(&b, "// LookupHint field. DO NOT EDIT by hand -- edit the Registry entry's")
	fmt.Fprintln(&b, "// LookupHint instead and re-run `go generate ./conformance/...`.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// Package lookuphints is UBI-20 workstream 3's shipped teaching-error")
	fmt.Fprintln(&b, "// data: for a handful of AWS resource types, the natural-key attribute")
	fmt.Fprintln(&b, "// name(s) (Terraform's own attribute, e.g. \"bucket\"/\"name\") that read")
	fmt.Fprintln(&b, "// back null when supplied alone, without \"id\" -- see cli/lookup.mdx in")
	fmt.Fprintln(&b, "// ubiquex-docs for the full human-readable table this is generated")
	fmt.Fprintln(&b, "// alongside. This package has zero runtime dependency on")
	fmt.Fprintln(&b, "// conformance -- that package is explicitly test-only tooling (see its")
	fmt.Fprintln(&b, "// own doc comment), never imported by shipped product code. Promoting")
	fmt.Fprintln(&b, "// the DATA into a small generated table here, rather than importing the")
	fmt.Fprintln(&b, "// package directly, keeps that boundary intact while still avoiding a")
	fmt.Fprintln(&b, "// hand-duplicated copy that could drift from what conformance actually")
	fmt.Fprintln(&b, "// verified.")
	fmt.Fprintln(&b, "package lookuphints")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// hints maps a resource type to its natural-key attribute(s) that read")
	fmt.Fprintln(&b, "// back null when supplied alone in --lookup, without \"id\".")
	fmt.Fprintln(&b, "var hints = map[string][]string{")
	for _, e := range entries {
		fmt.Fprintf(&b, "\t%q: {", e.typ)
		for i, attr := range e.extra {
			if i > 0 {
				fmt.Fprint(&b, ", ")
			}
			fmt.Fprintf(&b, "%q", attr)
		}
		fmt.Fprintln(&b, "},")
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// For returns resourceType's natural-key attribute(s) known to read back")
	fmt.Fprintln(&b, "// null when supplied alone in --lookup (without \"id\"), and whether any")
	fmt.Fprintln(&b, "// are known at all. A false ok means \"id\" alone is the verified shape,")
	fmt.Fprintln(&b, "// not that this type was never checked -- see cli/lookup.mdx for what")
	fmt.Fprintln(&b, "// \"verified\" means here.")
	fmt.Fprintln(&b, "func For(resourceType string) ([]string, bool) {")
	fmt.Fprintln(&b, "\th, ok := hints[resourceType]")
	fmt.Fprintln(&b, "\treturn h, ok")
	fmt.Fprintln(&b, "}")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "gentool: formatting generated source: %v\n", err)
		os.Exit(2)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gentool: %v\n", err)
		os.Exit(2)
	}
}
