// Code generated by conformance/gentool from conformance.Registry's
// LookupHint field. DO NOT EDIT by hand -- edit the Registry entry's
// LookupHint instead and re-run `go generate ./conformance/...`.

// Package lookuphints is UBI-20 workstream 3's shipped teaching-error
// data: for a handful of AWS resource types, the natural-key attribute
// name(s) (Terraform's own attribute, e.g. "bucket"/"name") that read
// back null when supplied alone, without "id" -- see cli/lookup.mdx in
// ubiquex-docs for the full human-readable table this is generated
// alongside. This package has zero runtime dependency on
// conformance -- that package is explicitly test-only tooling (see its
// own doc comment), never imported by shipped product code. Promoting
// the DATA into a small generated table here, rather than importing the
// package directly, keeps that boundary intact while still avoiding a
// hand-duplicated copy that could drift from what conformance actually
// verified.
package lookuphints

// hints maps a resource type to its natural-key attribute(s) that read
// back null when supplied alone in --lookup, without "id".
var hints = map[string][]string{
	"aws_iam_role":  {"name"},
	"aws_iam_user":  {"name"},
	"aws_s3_bucket": {"bucket"},
}

// For returns resourceType's natural-key attribute(s) known to read back
// null when supplied alone in --lookup (without "id"), and whether any
// are known at all. A false ok means "id" alone is the verified shape,
// not that this type was never checked -- see cli/lookup.mdx for what
// "verified" means here.
func For(resourceType string) ([]string, bool) {
	h, ok := hints[resourceType]
	return h, ok
}
